---
# tasks file for SNMP


- name: set up SNMP on network devices
  ios_config:
    lines:
      - snmp-server group G1 v3 priv
      - snmp-server user U1 G1 v3 auth sha a-pass priv aes 128 e-pass
  tags: priv

- name: set up SNMP on network devices
  ios_config:
    lines:      
      - snmp-server host 192.168.122.116 public
      - snmp-server enable traps
      - snmp-server enable traps snmp
  tags: traps
  
- name: Write Memory
  ios_command:
    commands: wr 

