---
# tass file for hostnames

- name: create hostnames in /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
  - 192.168.122.5 mgmnt
  - 192.168.122.1 R1
  - 192.168.86.10 S1
  - 192.168.86.11 S2
  - 192.168.86.12 S3
  - 192.168.86.13 S4
  - 192.168.86.14 S5
  - 192.168.86.15 S6
  register: output

- name: debug
  debug:
    var: output

