- name: main playbook for roles
  hosts: switches
  gather_facts: false
  
  tasks:
    - name: delete OSPF
      ios_config:
        lines: no network {{ dynamic_routing.ip }}
        parents: router OSPF 1
