- name: main playbook for roles
  hosts: switches
  gather_facts: false
  
  tasks:
    - name: delete OSPF
      ios_config:
        lines: no router OSPF 1

    - name: delete SNMP server
      ios_config:
        lines: no snmp-server
