- name: main playbook for roles
  hosts: switches
  gather_facts: false
  tasks:

    - name: Set OSPF with OSPFv2 resource module
      ios_ospfv2:
        config:
          processes:
            - process_id: 1            
              adjacency:  
                max_adjacency: 25
              network:
                - address: 10.0.0.0
                - wildcard_bits: 0.255.255.255
                - area: 0

    - name: Gather OSPFV2 provided configurations
      cisco.ios.ios_ospfv2:
        config:
          state: gathered
      register: output
    
    - name: debug
      debug:
        var: output 
