- name: main playbook for roles
  hosts: switches
  gather_facts: false
  tasks:

- name: Merge provided OSPF V2 configuration
  cisco.ios.ios_ospfv2:
    config:
      processes:
      - process_id: 1
        max_metric:
          router_lsa: true
          on_startup:
            time: 110
        areas:
        - area_id: '1'
          capability: true
          authentication:
            enable: true
        network:
          address: 10.0.0.0
          wildcard_bits: 0.0.0.0
          area: 1

    - name: Gather OSPFV2 provided configurations
      cisco.ios.ios_ospfv2:
        config:
        state: gathered
      register: output
    
    - name: debug
      debug:
        var: output 
