- name: main playbook for roles
  hosts: switches
  gather_facts: false
  tasks:

    - name: Gather OSPFV2 provided configurations
      cisco.ios.ios_ospfv2:
        config:
        state: gathered
      register: output
    
    - name: debug
      debug:
        var: output 
