---
- name: syslog
  ios_logging:
    dest: monitor
    level: warnings
    name: 192.168.122.124
    state: present


- name: change trap level on syslog
  ios_config:
    lines: 
      - no logging console
      - logging buffered 5000 warnings
  tags: cisco

- name: change trap level on syslog
  vios_config:
    lines: 
      - no logging console
      - logging buffered 5000 warnings
  tags: vios













