---
- name: syslog
  ios_logging:
    dest: monitor
    level: warnings
    name: 192.168.122.124
    state: present


- name: change trap level on syslog
  ios_config:
    lines: 
      - logging console












